[package]
name = "rustOS"
version = "0.1.0"
edition = "2018"

[dependencies]

# 使用cargo build编译时需要的配置
[profile.dev]
panic = "abort"  # 禁用panic时栈展开

# 使用cargo build --release编译时需要的配置
[profile.release]
panic = "abort"  # 禁用panic时栈展开