// Auto-generated by build.rs
pub const APP_NAMES: &[&str] = &[
    "00_hello_world", 
    "01_store_fault", 
    "02_power", 
    "03_priv_inst", 
    "04_priv_csr", 
    "05_printstack_test", 
    "06_taskinfo_test", 
];
