[package]
name = "NimlothOS"
description = "A simple operating system written in Rust"
version = "0.1.0"
authors = ["Jason Zhang <tinuvile@outlook.com>"]
edition = "2024"
repository = "https://github.com/tinuvile/NimlothOS"
readme = "README.md"

[dependencies]