[package]
name = "os"
description = "A simple operating system written in Rust"
version = "0.1.0"
authors = ["Jason Zhang <tinuvile@outlook.com>"]
edition = "2024"
repository = "https://github.com/tinuvile/NimlothOS"
readme = "README.md"

[dependencies]
rustsbi = { version = "0.4.0", features = ["machine"] }

[profile.release]
debug = true