[package]
name = "os"
description = "A simple operating system written in Rust"
version = "0.1.0"
authors = ["Jason Zhang <tinuvile@outlook.com>"]
edition = "2024"

[dependencies]
rustsbi = { version = "0.4.0", features = ["machine"] }
log = "0.4"

[profile.release]
debug = true