name: Code

on:
  push:
  pull_request:
  schedule:
    - cron: "00 10 * * *" # every day at 10:00

jobs:
  check:
    name: Check

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - run: rustup target add riscv64gc-unknown-none-elf
      - run: cargo check --target riscv64gc-unknown-none-elf

  test:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - run: rustup target add riscv64gc-unknown-none-elf
      - run: cargo build --target riscv64gc-unknown-none-elf

  fmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: rustup target add riscv64gc-unknown-none-elf
      - run: rustup component add clippy
      - run: cargo clippy --target riscv64gc-unknown-none-elf